/**
 * A pure, LOCAL renderer for a preview NSIS script from `NsisSpec` + `NsisLocalPaths`.
 *
 * Deliberately not the sibling lane's `renderNsis` in `src/core/nsis` (which does not exist in
 * this worktree) -- this is this branch's own read-only preview generator, kept intentionally
 * small and pure (string in, string out, no fs/IPC) so it is trivial to test and to reconcile
 * later against the sibling's real spec/renderer.
 */

import type { NsisCompression, NsisInstallRoot, NsisLocalPaths, NsisSpec } from './nsis-form-types'

const INSTALL_ROOT_DIR: Record<NsisInstallRoot, string> = {
  'program-files-64': '$PROGRAMFILES64',
  'program-files-32': '$PROGRAMFILES',
  'local-app-data': '$LOCALAPPDATA',
  'per-user-program-files': '$LOCALAPPDATA\\Programs'
}

const COMPRESSION_DIRECTIVE: Record<NsisCompression, string> = {
  lzma: 'SetCompressor /SOLID lzma',
  zlib: 'SetCompressor zlib',
  bzip2: 'SetCompressor bzip2',
  none: 'SetCompress off'
}

/** Quotes a value for an NSIS string literal: backslashes are literal in NSIS strings (no escape
 *  needed), so only the double-quote itself has to be neutralized. */
function nsisQuote(value: string): string {
  return '"' + value.split('"').join('$\\"') + '"'
}

/** NSIS's `VIProductVersion` requires exactly four dot-separated numeric parts. Pads or trims
 *  whatever the user typed rather than rejecting it -- this is a read-only preview, not a
 *  validator. */
function fourPartVersion(version: string): string {
  const parts = version.split('.').map((p) => p.trim() || '0')
  while (parts.length < 4) parts.push('0')
  return parts.slice(0, 4).join('.')
}

function safeOutputFileName(spec: NsisSpec): string {
  const trimmed = spec.outputFileName.trim()
  if (trimmed) return trimmed
  const base = spec.appName.trim() || 'App'
  return base.replace(/[^A-Za-z0-9._-]+/g, '-') + '-Setup.exe'
}

/**
 * Renders a preview `.nsi` script. Always produces SOMETHING -- missing fields render as inline
 * `; TODO:` placeholders rather than an empty box, per the guided-form rule that a disabled/empty
 * state must say plainly what is missing rather than showing nothing.
 *
 * Built with plain string concatenation (`+`), not template-literal interpolation, for every line
 * that mixes an NSIS `$Variable` with a JS-interpolated value: `` `$SMPROGRAMS\${x}` `` is a real
 * trap (backslash-dollar escapes the `$`, so `${x}` renders as the literal text `${x}` instead of
 * interpolating) and `` `$INSTDIR\Uninstall.exe` `` is a second one (`\U` is not a recognized JS
 * escape, so the backslash is silently dropped). Both bit this file on the first pass and were
 * caught by the round-trip test below going red; concatenation has no escape sequence to get
 * wrong.
 */
export function renderNsisPreview(spec: NsisSpec, local: NsisLocalPaths): string {
  const lines: string[] = []
  const version = spec.version.trim() || '0.0.0'
  const publisher = spec.publisher.trim()
  const outFile = safeOutputFileName(spec)
  const appDirName = spec.appName.trim() || 'YourApp'
  const installDir = INSTALL_ROOT_DIR[spec.installRoot] + '\\' + appDirName

  lines.push('; Generated by nodeterm\'s NSIS installer builder node -- preview only.')
  lines.push('Name ' + nsisQuote(spec.appName.trim() || 'Your App'))
  lines.push('OutFile ' + nsisQuote(outFile))
  lines.push('InstallDir ' + nsisQuote(installDir))
  lines.push('RequestExecutionLevel ' + (spec.perMachine ? 'admin' : 'user'))
  lines.push(COMPRESSION_DIRECTIVE[spec.compression])
  lines.push('')
  lines.push('VIProductVersion ' + nsisQuote(fourPartVersion(version)))
  lines.push('VIAddVersionKey "ProductName" ' + nsisQuote(spec.appName.trim() || 'App'))
  lines.push('VIAddVersionKey "ProductVersion" ' + nsisQuote(version))
  if (publisher) lines.push('VIAddVersionKey "CompanyName" ' + nsisQuote(publisher))
  lines.push('')

  if (local.licensePath) {
    lines.push('Page license')
    lines.push('LicenseData ' + nsisQuote(local.licensePath))
  }
  lines.push('Page directory')
  lines.push('Page instfiles')
  lines.push('')

  if (local.iconPath) {
    lines.push('Icon ' + nsisQuote(local.iconPath))
    lines.push('UninstallIcon ' + nsisQuote(local.iconPath))
    lines.push('')
  }

  lines.push('Section "Install"')
  lines.push('  SetOutPath "$INSTDIR"')
  if (local.sourcePaths.length === 0) {
    lines.push('  ; TODO: add at least one source file or folder to package')
  } else {
    for (const p of local.sourcePaths) {
      lines.push('  File /r ' + nsisQuote(p))
    }
  }
  if (spec.includeUninstaller) {
    lines.push('  WriteUninstaller "$INSTDIR\\Uninstall.exe"')
  }
  if (spec.createStartMenuShortcut) {
    const menuName = spec.appName.trim() || 'App'
    lines.push('  CreateDirectory "$SMPROGRAMS\\' + menuName + '"')
    lines.push(
      '  CreateShortCut "$SMPROGRAMS\\' + menuName + '\\' + menuName + '.lnk" "$INSTDIR\\' + menuName + '.exe"'
    )
  }
  if (spec.createDesktopShortcut) {
    const appTitle = spec.appName.trim() || 'App'
    lines.push('  CreateShortCut "$DESKTOP\\' + appTitle + '.lnk" "$INSTDIR\\' + appTitle + '.exe"')
  }
  lines.push('SectionEnd')

  if (spec.includeUninstaller) {
    lines.push('')
    lines.push('Section "Uninstall"')
    lines.push('  Delete "$INSTDIR\\Uninstall.exe"')
    lines.push('  RMDir /r "$INSTDIR"')
    if (spec.createStartMenuShortcut) {
      const menuName = spec.appName.trim() || 'App'
      lines.push('  RMDir /r "$SMPROGRAMS\\' + menuName + '"')
    }
    if (spec.createDesktopShortcut) {
      const appTitle = spec.appName.trim() || 'App'
      lines.push('  Delete "$DESKTOP\\' + appTitle + '.lnk"')
    }
    lines.push('SectionEnd')
  }

  return lines.join('\n')
}
