// Shared types for the WSL distribution-management bridge. No Node/Electron imports — safe for
// the renderer, and the single place both the core service (src/core/wsl/service.ts) and the
// renderer consumer (src/renderer/wsl/wslCoreApi.ts) agree on what crosses the IPC/RPC boundary.
//
// These shapes are DELIBERATELY narrower than the full `src/core/wsl/*` package's own types
// (WslInstalledDistribution, WslCreateRequest, WslDeleteIntent, …): they are what the canvas UI
// actually consumes, adapted from core's more defensive internal contract at the service layer.
// See `src/core/wsl/service.ts`'s header comment for exactly which fields are dropped and why.

export type WslInstanceState = 'running' | 'stopped'

export interface WslInstanceSummary {
  name: string
  state: WslInstanceState
  /** From the core service's own durable ownership ledger, re-read fresh on every enumeration —
   *  never inferred from a name, a prefix, or anything persisted in a shared project file. */
  ownedByApp: boolean
  memoryMb?: number
}

export interface WslCatalogueEntry {
  /** The exact machine name `wsl --install -d <name>` expects — Windows' own catalog has no
   *  separate opaque package id, so the catalog NAME is reused verbatim as the create-time id. */
  id: string
  /** Human-readable name for the picker, e.g. "Ubuntu 24.04 LTS". */
  label: string
}

export type WslCreateStage =
  | 'validating'
  | 'checking'
  | 'installing'
  | 'recording'
  | 'completed'
  | 'failed'
  | 'cancelled'

/** Localizable ids emitted by the host. The host sends data, never already-rendered English. */
export type WslCreateProgressMessageId =
  | 'validating'
  | 'checking'
  | 'installing'
  | 'recording'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'cancelledLate'

export interface WslCreateProgressMessage {
  id: WslCreateProgressMessageId
  /** Placeholder values are runtime facts and are never passed through vocabulary replacement. */
  params: Readonly<Record<string, string>>
  /** Exact substrings in the formatted message that must remain byte-for-byte unchanged. */
  facts: readonly string[]
}

export type WslCreateErrorCode =
  | 'invalid-operation-id'
  | 'duplicate-operation'
  | 'validation-failed'
  | 'catalogue-unavailable'
  | 'cancelled'
  | 'create-failed'
  | 'ownership-record-failed'

export interface WslCreateError {
  code: WslCreateErrorCode
  message: WslCreateProgressMessage
}

export type WslCatalogueErrorCode = 'not-installed' | 'command-failed' | 'parse-failed'

export interface WslCatalogueError {
  code: WslCatalogueErrorCode
  messageId: 'catalogueNotInstalled' | 'catalogueCommandFailed' | 'catalogueParseFailed'
  /** Exact executable and parser diagnostics, retained outside authored copy. */
  facts: readonly string[]
  detail?: string
}

export interface WslCreateProgress {
  operationId: string
  stage: WslCreateStage
  step: number
  steps: number
  /** True only for phases with measured progress. WSL installation itself has no byte telemetry. */
  determinate: boolean
  elapsedMs: number
  message: WslCreateProgressMessage
  error?: WslCreateError
}

/** Operation ids are generated by the renderer with crypto.randomUUID(), which is UUID v4.
 * Rejecting other valid UUID versions keeps the cancellation map scoped to this exact contract. */
export function isWslCreateOperationId(value: unknown): value is string {
  return typeof value === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)
}

export type WslActionResult = { ok: true } | { ok: false; error: string }
export type WslCreateResult = { ok: true; name: string } | { ok: false; error: WslCreateError }

export interface WslApi {
  /** Every installed distribution on this machine, this app's own and pre-existing ones alike.
   *  REJECTS (never resolves to an empty array) when the machine could not actually be read —
   *  WSL missing, wsl.exe erroring, output that could not be parsed. "We looked and there is
   *  nothing" and "we could not look" are different facts, and a caller (see
   *  `src/renderer/state/wsl.ts`) must be able to tell them apart. */
  list(): Promise<WslInstanceSummary[]>
  /** Every distribution `wsl --install -d <name>` could install. Rejects on the same terms as
   *  `list()` — a failed catalog read must never resolve to an empty, healthy-looking list. */
  catalogue(): Promise<WslCatalogueEntry[]>
  create(input: { operationId: string; catalogueId: string; name: string }): Promise<WslCreateResult>
  cancelCreate(operationId: string): Promise<boolean>
  onCreateProgress(listener: (progress: WslCreateProgress) => void): () => void
  sleep(name: string): Promise<WslActionResult>
  wake(name: string): Promise<WslActionResult>
  /** The core service refuses this itself when `name` is not app-owned, in addition to the UI
   *  never offering the control for one. */
  delete(name: string): Promise<WslActionResult>
}
