import { describe, expect, it } from 'vitest'
import { isWslCreateOperationId } from './wsl'

describe('isWslCreateOperationId', () => {
  it('accepts the UUID v4 shape generated by the renderer', () => {
    expect(isWslCreateOperationId('123e4567-e89b-42d3-a456-426614174000')).toBe(true)
  })

  it('rejects another valid UUID version', () => {
    expect(isWslCreateOperationId('123e4567-e89b-12d3-a456-426614174000')).toBe(false)
  })
})
