import { IPC } from '../../shared/ipc'
import type { CorePlatform } from '../platform'
import type { UniGetUiPackageInstallOptions } from '../../shared/unigetui'
import { UniGetUiClient } from './client'
import { UniGetUiUniverseStore } from './store'

/** Register the machine-owned UniGetUI Global Universe. No handler accepts activeProjectId. */
export function registerUniGetUiIpc(platform: CorePlatform): { client: UniGetUiClient; store: UniGetUiUniverseStore } {
  const client = new UniGetUiClient()
  const store = new UniGetUiUniverseStore(platform.userDataDir)
  platform.handle(IPC.unigetuiStatus, () => client.status())
  platform.handle(IPC.unigetuiUniverseState, () => store.load())
  platform.handle(IPC.unigetuiSaveUniverseState, (state) => store.save(state))
  platform.handle(IPC.unigetuiAppStatus, () => client.appStatus())
  platform.handle(IPC.unigetuiNavigate, (page) => client.navigate(page))
  platform.handle(IPC.unigetuiOperations, () => client.operations())
  platform.handle(IPC.unigetuiOperation, (id) => client.operation(id))
  platform.handle(IPC.unigetuiOperationOutput, (id, tail) => client.operationOutput(id, tail))
  platform.handle(IPC.unigetuiOperationWait, (id, timeout) => client.operationWait(id, timeout))
  platform.handle(IPC.unigetuiOperationCancel, (id) => client.operationCancel(id))
  platform.handle(IPC.unigetuiOperationRetry, (id, mode) => client.operationRetry(id, mode))
  platform.handle(IPC.unigetuiOperationReorder, (id, action) => client.operationReorder(id, action))
  platform.handle(IPC.unigetuiOperationForget, (id) => client.operationForget(id))
  platform.handle(IPC.unigetuiManagers, () => client.managers())
  platform.handle(IPC.unigetuiManagerAction, (manager, action, input) => client.managerAction(manager, action, input))
  platform.handle(IPC.unigetuiSources, (manager) => client.sources(manager))
  platform.handle(IPC.unigetuiSourceAdd, (manager, name, url) => client.sourceAdd(manager, name, url))
  platform.handle(IPC.unigetuiSourceRemove, (manager, name, url) => client.sourceRemove(manager, name, url))
  platform.handle(IPC.unigetuiSettings, () => client.settings())
  platform.handle(IPC.unigetuiSettingGet, (key) => client.settingGet(key))
  platform.handle(IPC.unigetuiSettingSet, (key, input) => client.settingSet(key, input))
  platform.handle(IPC.unigetuiSettingClear, (key) => client.settingClear(key))
  platform.handle(IPC.unigetuiSettingsReset, () => client.settingsReset())
  platform.handle(IPC.unigetuiShortcuts, () => client.shortcuts())
  platform.handle(IPC.unigetuiShortcutSet, (path, status) => client.shortcutSet(path, status))
  platform.handle(IPC.unigetuiShortcutReset, (path) => client.shortcutReset(path))
  platform.handle(IPC.unigetuiShortcutResetAll, () => client.shortcutResetAll())
  platform.handle(IPC.unigetuiLogs, (kind, manager, level) => client.logs(kind, manager, level))
  platform.handle(IPC.unigetuiBackups, () => client.backups())
  platform.handle(IPC.unigetuiBackupLocalCreate, () => client.backupLocalCreate())
  platform.handle(IPC.unigetuiBundle, () => client.bundle())
  platform.handle(IPC.unigetuiBundleReset, () => client.bundleReset())
  platform.handle(IPC.unigetuiBundleImport, (input) => client.bundleImport(input))
  platform.handle(IPC.unigetuiBundleExport, (path) => client.bundleExport(path))
  platform.handle(IPC.unigetuiBundleAdd, (input) => client.bundleAdd(input))
  platform.handle(IPC.unigetuiBundleRemove, (input) => client.bundleRemove(input))
  platform.handle(IPC.unigetuiBundleInstall, (input) => client.bundleInstall(input))
  platform.handle(IPC.unigetuiPackageSearch, (query, manager, maxResults) => client.packageSearch(query, manager, maxResults))
  platform.handle(IPC.unigetuiPackageDetails, (id, manager, source) => client.packageDetails(id, manager, source))
  platform.handle(IPC.unigetuiPackageVersions, (id, manager, source) => client.packageVersions(id, manager, source))
  platform.handle(IPC.unigetuiPackageInstalled, (manager) => client.packageInstalled(manager))
  platform.handle(IPC.unigetuiPackageUpdates, (manager) => client.packageUpdates(manager))
  platform.handle(IPC.unigetuiPackageInstall, (id, options: UniGetUiPackageInstallOptions) => client.packageInstall(id, options))
  platform.handle(IPC.unigetuiPackageDownload, (id, options: UniGetUiPackageInstallOptions & { output?: string }) => client.packageDownload(id, options))
  platform.handle(IPC.unigetuiPackageUpdate, (id, options: UniGetUiPackageInstallOptions) => client.packageUpdate(id, options))
  platform.handle(IPC.unigetuiPackageUninstall, (id, manager, options) => client.packageUninstall(id, manager, options))
  platform.handle(IPC.unigetuiPackageRepair, (id, manager, options) => client.packageRepair(id, manager, options))
  return { client, store }
}
