#!/bin/bash
# Wires the host keys and per-user authorized_keys generated by run.sh (bind-mounted read-only
# under /keys) into the locations and ownership sshd requires, then execs sshd in the foreground.
#
# Host keys and authorized_keys are COPIED rather than used in place because sshd's StrictModes
# check requires the authorized_keys file (and its .ssh dir) to be owned by the target user, and a
# bind-mounted file keeps its host-side owning UID, which will not match the in-container user.
# Copying lets us chown/chmod freshly inside the container regardless of the host UID.
set -euo pipefail

install -d -m 700 /etc/ssh/host_keys
install -m 600 /keys/host/ssh_host_ed25519_key /etc/ssh/host_keys/ssh_host_ed25519_key
install -m 644 /keys/host/ssh_host_ed25519_key.pub /etc/ssh/host_keys/ssh_host_ed25519_key.pub

for u in keyuser passuser; do
  install -d -m 700 -o "$u" -g "$u" "/home/$u/.ssh"
  install -m 600 -o "$u" -g "$u" "/keys/clientkeys/$u.pub" "/home/$u/.ssh/authorized_keys"
done

exec /usr/sbin/sshd -D -e
